### ISSUE TITLE
학교의 풀 네임이 다른 학교의 것과 동일할 때 사용이 불가능합니다.

### ISSUE THREAD

**Issue by HexagonWin** [Coder-Iro/comcigan-py#10]
안녕하세요. 해당 라이브러리 사용중 문제를 해결할 수 없어 이슈 남깁니다.
학교의 이름이 다른 학교와 동일할 때, 학교명을 설정할 수 없습니다.
(예시 : [인천] 신흥중학교, [경기] 신흥중학교, [대전] 대전원신흥중학교)
이와 같은 경우 "신흥중학교"로 설정시 여러 학교가 검색되어 설정이 되지 않습니다.
관련 문제 해결이 가능한가요? (지역별 구별 등)
감사합니다.

**Comment by kms0219kms** [comment]
#7 에서 해결된 이슈네요.
