### ISSUE TITLE
컴시간 사이트 업데이트로 인한 오류

### ISSUE THREAD

**Issue by khw2ok** [Coder-Iro/comcigan-py#11]
라이브러리를 잘 이용하고 있었는데, 하필 개학 전 날에 오류가 나더군요.

아래와 같은 코드 실행 시.
```python
from comcigan import School

myschool = School("봉원중학교")
print(myschool.name)
print(myschool[2][3][3][3])
```

아래와 같은 오류가 발생합니다.
```bash
Traceback (most recent call last):
  File "/home/nickid/Documents/bongwonbot/test.py", line 1, in <module>
    from comcigan import School
  File "/home/nickid/Documents/bongwonbot/.venv/lib/python3.11/site-packages/comcigan/__init__.py", line 1, in <module>
    from .school import School
  File "/home/nickid/Documents/bongwonbot/.venv/lib/python3.11/site-packages/comcigan/school.py", line 33, in <module>
    script = comcigan_html.find_all("script")[1].contents[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

아마도 컴시간 사이트를 업데이트 한 걸로 인한 오류 인 것 같네요.
![스크린샷 2023-03-01 10-10-01](https://user-images.githubusercontent.com/92078139/222022851-d21e3e81-f8f5-41be-94f6-3fc6ade50e7e.png)

**Comment by kms0219kms** [comment]
구조 변경과 함께 아이피가 변경된거로 보여 해당 부분 PR을 드릴 예정입니다. 확인하고 머지 해주시면 감사드리겠습니다.
112.186.146.81 -> 112.186.226.178, comci.kr -> comci.net

146.81과 거기에 매치되는 comci.kr은 현재 L4 로드밸런서 스위칭 분기가 되는데, 일부 로드밸런서는 아직 신규도메인/아이피로 포워딩 해주고 있지 않아 간헐적으로 오류가 나는 것으로 보여

확실하게 신규 아이피로 밀고 나가는 쪽으로 PR 드리고자 합니다.

**Comment by kms0219kms** [comment]
#12

**Comment by Coder-Iro** [comment]
컴시간 재밌네요 일정 확률로 새로고침하는 html을 보내게 해둔거 같은데 지금 이슈에서 제시된 오류가 그것때매 발생하는것 같아요. 크롤링을 방지하려는 목적인거 같은데 참.. User-Agent 체크는 안하면서 이상한 짓만 하네요

**Comment by kms0219kms** [comment]
정확히는 로드밸런서 중 몇대는 신규 서버로 포워딩 들어간겁니다

**Comment by kms0219kms** [comment]
그래서 제가 아예 신규 서버로 아이피 변경하는 PR을 드렸던 겁니다

**Comment by Coder-Iro** [comment]
일단은 주소 PR은 받았는데 사이트 구조개편 대응도 해야되는데 재수생이라 시간이 잘 안나네요 최대한 빨리 픽스를 해보도록 할게요

**Comment by kms0219kms** [comment]
수고하십니다.

**Comment by kms0219kms** [comment]
일단 정상작동만 확인되면 이 이슈는 닫아둡시다. 추후에 컴시간 구조가 더 바뀌면 그때 다시 열어서 작업하는거로 하죠

**Comment by Coder-Iro** [comment]
지금 리팩토링하는 중이라 그거 끝나면 닫으려고 했는데요 일단 닫는걸로할까요?

> 일단 정상작동만 확인되면 이 이슈는 닫아둡시다. 추후에 컴시간 구조가 더 바뀌면 그때 다시 열어서 작업하는거로 하죠

**Comment by kms0219kms** [comment]
리팩토링에 컴시간 구조 변경에 대한 알고리즘 개선이 중심이 되나요? 아니라면 리팩토링은 새 이슈에서 이야기 하는게 추후 기록 보관애도, 관리하기도 편할거 같아요.
